### ISSUE TITLE
Importing this package breaks due to incorrect "main" and "typings"

### ISSUE THREAD

**Issue by mikeporterdev** [TypeStrong/ts-mockito#24]
In the latest version, the package cannot be imported as the "main" and "typings" values of the package.json point to an invalid path. It looks like they're pointing to a lib folder which does not exist in what has been submitted to npm. I can see the lib folder is generated on source compilation but it looks like the project pushes one level lower to npm.

This should either be fixed by changing the package.json to point at the right place, or re-pushing with the lib folder to npm. I will submit a PR for the former but feel free to go with the latter

**Comment by mikeporterdev** [comment]
An error of the image 
![image](https://user-images.githubusercontent.com/6642457/183459192-11a9f737-ae3d-493d-a799-e564b72d7a33.png)
![image](https://user-images.githubusercontent.com/6642457/183459229-ff84f607-1a99-4512-84ec-cb0bf89863ad.png)

Picture of the package.json after install and the missing lib folder in the installed content 
![image](https://user-images.githubusercontent.com/6642457/183459425-f0588725-9a75-4c9e-9a4d-703dfca41eb8.png)

**Comment by pauleustice** [comment]
I noticed this yesterday. I'd suggest the latter option (changing the directory structure), as that mimics what's in the original ts-mockito package as well as keeping package files (like `package.json`) separate from lib files.

**Comment by cspotcode** [comment]
Pinging @LironHazan, she might have some insight here.

@mikeporterdev can we trace down exactly where this issue was introduced?  Was the tsconfig file changes?  Are any code changes necessary, or is it a matter of rebuilding and republishing?

Unkpg.com links might help.

**Comment by mikeporterdev** [comment]
Thanks @cspotcode 

This arose in your latest version as far as I can tell
https://unpkg.com/@typestrong/ts-mockito@2.6.2/lib/ts-mockito.js
https://unpkg.com/@typestrong/ts-mockito@2.6.3/lib/ts-mockito.js

It looks to be that when the package was deployed, files were not in the same structure as they were expected by the package.json. It's possible the old project was doing some manual moving after building which is why the build/deploy didn't quite work this time.

The available solution seems to be one of the following:
Short term hack: Accept my PR and redeploy
Short term, slightly less hacky: Rebuild the package into a shape that matches the expectations of the package.json and redeploy
Long term: Fix the build process so that it builds it into the right shape for a deploy

**Comment by cspotcode** [comment]
Can someone look at the existing npm scripts and see what they do, if they emit files into the correct location?  Pulling the code, running a build, running`npm pack` should give you a tarball and useful diagnostic logging.

I'm not the one who did the most recent publication, and currently zi have zero time for this project.  Hence my questions.

**Comment by mikeporterdev** [comment]
Can confirm that an `npm build` puts files into a `lib` folder. `npm pack` then packages them into the tarball with them still in this `lib` folder.

**Comment by cspotcode** [comment]
Thanks.  If I had to guess, #22 is the culprit.  Will wait for confirmation from @LironHazan, to double-check what the intention was.  Possibly a revert of #22 is all we need to do.

**Comment by mikeporterdev** [comment]
It seems that the last npm publish was run from inside the `lib` directory, so as to only deploy the compiled js files, whereas the `main`/`typings` fields in the package.json are expecting that lib folder. 
It seems just a simple `npm build` and a redeploy from the root package would fix the issue, at least temporarily. As far as I can tell the deploys aren't part of a pipeline so far and are done manually? So it seems that there isn't necessarily a short term code fix to resolve this.

**Comment by mikeporterdev** [comment]
Just to note I would be happy to resolve this myself if others don't have the time, and if I am given access but I appreciate I am an untrusted contributor to the project.

**Comment by LironHazan** [comment]
@cspotcode @mikeporterdev Hey sorry for disappearing I was on a vacation and now back to work, I can give it a check later + @mikeporterdev sure you can open a PR (fork and open)

**Comment by mikeporterdev** [comment]
Thanks @LironHazan, I've already opened a PR when I first opened the issue, it's not the best solution but I think it's the only solution that can be done without having access to npm deploys myself.

**Comment by cspotcode** [comment]
I'm not sure what you mean by that, since any solution requires a re-publish of a new tarball.

**Comment by mikeporterdev** [comment]
I just mean that my change would mean you can deploy using whatever process you used to deploy the last release and it would work in place. The other solution requires a change in the process you use to deploy. 
Both solutions require a republishing of course

**Comment by LironHazan** [comment]
@mikeporterdev @cspotcode in the past I aimed to automate the publish processes as well in github actions on merge to master - I'll do that.
OK so the original structure is with lib, and the publish was done manually from lib (my bad!), umm though I kind of don't like it cause conventionally lib acts as "dist" in a way that it isn't a part of the repo but from other hand it's part of the published structure so in order to be aligned with the original fork I'll publish a new version in the same structure instead, though I don't like pointing to "lib" while it's not there and the term "lib" bugs me... wdyt?

**Comment by LironHazan** [comment]
@mikeporterdev @cspotcode @pauleustice here's a suggested fix --> https://github.com/TypeStrong/ts-mockito/pull/27
it should fit but let me know what you think before merging and bumping up the version, once that will be merged I'll add the auto publishing github action and we'll stop publishing manually!

**Comment by mikeporterdev** [comment]
@LironHazan PR looks good! and yeah definitely in favour of a code controlled automated publish over a manual. 
Agreed that "lib" is a bit odd.
I've closed my PR :)

**Comment by LironHazan** [comment]
@mikeporterdev cool, I merged but the publish failed, there's a chance that the version bumpup should be manual, I'll try tweaking that

**Comment by LironHazan** [comment]
The new version was published via gha :) thanks all!
