### ISSUE TITLE
Where are the release notes?

### ISSUE THREAD

**Issue by distante** [TypeStrong/ts-mockito#30]
Hi, I see in [npm that the latest version is 2.6.4](https://www.npmjs.com/package/@typestrong/ts-mockito) but [the tags page of the repo](https://github.com/TypeStrong/ts-mockito/tags) just contains [v2.6.1](https://github.com/TypeStrong/ts-mockito/releases/tag/v2.6.1).

Where are the release notes and changes of this fork?

Greetings!

**Comment by LironHazan** [comment]
@distante Hey we were hoping to be merged back to the original repo but as that probably won't happen, @cspotcode kindly added this project to typestrong and here we are today :)
I'll try to go over the additional commits in near future (mainly fixes) and tackle that,  
Thanks for raising that point..

**Comment by LironHazan** [comment]
https://github.com/TypeStrong/ts-mockito/releases/tag/v2.6.4
