### ISSUE TITLE
How to mock a standalone function?

### ISSUE THREAD

**Issue by mebble** [TypeStrong/ts-mockito#36]
I want to mock a standalone function (i.e. a function that's not a method of some object) but I can't find information on that in the readme.

Here is a simplified version of what I'm trying to do:

```ts
type Callback = (x: number) => void;

const caller = (callback: Callback) => {
    callback(Math.random())
}

let mockCallback: Callback = mock<Callback>();

caller(mockCallback);            // fails when using mock without instance
caller(instance(mockCallback));  // fails when using mock with instance
caller(x => console.log(x))      // works when not using a mock
```

As shown above, the first two `caller(...)` calls that use the mock would fail. They fail with the error:

```
TypeError: callback is not a function
 ❯ caller src/test.test.ts:7:5
      5|
      6| const caller = (callback: Callback) => {
      7|     callback(Math.random())
       |     ^
      8| }
```

I want to mock a standalone function so that I can capture its arguments and do stuff with them. Could you please help me out? Thanks

**Comment by LironHazan** [comment]
@mebble Hey, 
This project is in maintenance mode as the original upstream isn't maintained at all, so in general there's no plan of adding new features (especially functionalities which are available in jest/vitest)  but there's a PR we can merge on that.

What do you think of the following?

```typescript
let fn: (a: number, b: string) => number = fnmock();
when(fn(10, 'hello')).thenReturn(5);
instance(fn)(10, 'hello'); // returns 5
verify(fn(10, 'hello')).called();
```
I can port that and release another version

**Comment by mebble** [comment]
Yeah this API seems consistent with how we mock objects. You must be referring to PR https://github.com/TypeStrong/ts-mockito/pull/7?

I switched to [vitest mocks](https://vitest.dev/api/mock.html) as you mentioned. In case someone runs into this, here's how to mock and capture in vitest:

```ts
import { vi, Mock } from 'vitest';

type Callback = (x: number) => void;

const caller = (callback: Callback) => {
    callback(Math.random())
}

const mockCallback: Mock<Parameters<Callback>, ReturnType<Callback>> = vi.fn();

// inject the mock
caller(mockCallback);

// capture the mock's calls
const [randomNum] = mockCallback.mock.lastCall!
```

I think we can close this issue if the discussion on `fnmock` is in PR#7
