### ISSUE TITLE
Using regex to parse code is bad practice, should be done with JS parser and AST

### ISSUE THREAD

**Issue by roypeled** [TypeStrong/ts-mockito#44]
The regex parsing engine was not handling compiled code correctly, it would extract malformed tokens when self invoked functions and compiled imported modules were introduced in the code ((0, imported)(arg)).

I created a PR to fix the issue here: 
https://github.com/TypeStrong/ts-mockito/pull/43

**Comment by LironHazan** [comment]
Welcome Roy! I'm honored getting PRs from you!

**Comment by LironHazan** [comment]
I think your PR is also relevant to this thread btw   
https://github.com/TypeStrong/ts-mockito/pull/17
